<a href="https://colab.research.google.com/github/mqifjjfwiot/SeSAC_Data2/blob/master/Vectorize_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [ ]:
corpus = ["you know I want your love",
          "I like you",
          "what should I do",
          "I can't build it. Something's in the way",
          "Roger that",
          "This is crazy",
          "This is your plan?",
          "What? You run out of marines?"
]

In [ ]:
cv = CountVectorizer()

In [ ]:
#1. 사전을 만들어라! => fit()
#2. 사전에 들어있는 id로 인코딩하라! => transform()
#3. 1, 2를 함께 처리하고자 하는 경우 => fit_transform()

In [ ]:
vd = cv.fit_transform(corpus).toarray()
vd

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 1, 0, 0],
       [1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0]])

In [ ]:
cv.inverse_transform(vd)

[array(['know', 'love', 'want', 'you', 'your'], dtype='<U9'),
 array(['like', 'you'], dtype='<U9'),
 array(['do', 'should', 'what'], dtype='<U9'),
 array(['build', 'can', 'in', 'it', 'something', 'the', 'way'], dtype='<U9'),
 array(['roger', 'that'], dtype='<U9'),
 array(['crazy', 'is', 'this'], dtype='<U9'),
 array(['is', 'plan', 'this', 'your'], dtype='<U9'),
 array(['marines', 'of', 'out', 'run', 'what', 'you'], dtype='<U9')]

In [ ]:
cv.get_feature_names()

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['build',
 'can',
 'crazy',
 'do',
 'in',
 'is',
 'it',
 'know',
 'like',
 'love',
 'marines',
 'of',
 'out',
 'plan',
 'roger',
 'run',
 'should',
 'something',
 'that',
 'the',
 'this',
 'want',
 'way',
 'what',
 'you',
 'your']

In [ ]:
tfidf= TfidfVectorizer()

In [ ]:
# fit-->transform

In [ ]:
tfidf.fit(corpus)

TfidfVectorizer()

In [ ]:
tfidf.transform(corpus)

<8x26 sparse matrix of type '<class 'numpy.float64'>'
	with 32 stored elements in Compressed Sparse Row format>

In [ ]:
tfidf.transform(corpus).toarray()

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.48648224, 0.        , 0.48648224,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.48648224, 0.        , 0.        , 0.35182035,
        0.40771009],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.81030585, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.58600719,
        0.        ],
       [0.        , 0.        , 0.        , 0.60831315, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.60831315, 0.        , 0.        , 0.        ,
      

In [ ]:
sentence = ["I like like like marines"]

In [ ]:
nd2array = cv.transform(sentence).toarray()
nd2array

array([[0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0]])

In [ ]:
nd2array[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [ ]:
nd2array[0][8]

3

In [ ]:
nd2array2 = tfidf.transform(sentence).toarray()
nd2array2

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.9486833 , 0.        ,
        0.31622777, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [ ]:
cv.inverse_transform(nd2array)

[array(['like', 'marines'], dtype='<U9')]

In [ ]:
tfidf.inverse_transform(nd2array2)

[array(['like', 'marines'], dtype='<U9')]

In [ ]:
feature_list = cv.get_feature_names()
feature_list

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


['build',
 'can',
 'crazy',
 'do',
 'in',
 'is',
 'it',
 'know',
 'like',
 'love',
 'marines',
 'of',
 'out',
 'plan',
 'roger',
 'run',
 'should',
 'something',
 'that',
 'the',
 'this',
 'want',
 'way',
 'what',
 'you',
 'your']

In [ ]:
# dic <-- list
dictionary = dict()

In [ ]:
for index, element in enumerate(feature_list):
  dictionary[index] = element
dictionary

{0: 'build',
 1: 'can',
 2: 'crazy',
 3: 'do',
 4: 'in',
 5: 'is',
 6: 'it',
 7: 'know',
 8: 'like',
 9: 'love',
 10: 'marines',
 11: 'of',
 12: 'out',
 13: 'plan',
 14: 'roger',
 15: 'run',
 16: 'should',
 17: 'something',
 18: 'that',
 19: 'the',
 20: 'this',
 21: 'want',
 22: 'way',
 23: 'what',
 24: 'you',
 25: 'your'}

In [ ]:
## 스팸을 나타내는 사전 만들기
## 스팸이 아닌 사전 만들기

In [ ]:
## 광고!! 짱 좋은 판매 홍보전략입니다.!! => 스팸입니다.!!

In [ ]:
spam_dict = ["광고","특별","홍보","절호","당신만의","폭탄","충격","세일","효능","허경영","특가","한정"]

In [ ]:
ham_dict= ["주문","확인","결제","검토","고객","배송","일반","동호회"]

In [ ]:
email = ["광고 !! 짱 좋은 판매 홍보 전략입니다.!!"]

In [ ]:
cv.fit(spam_dict)
cv.vocabulary_

{'광고': 0,
 '당신만의': 1,
 '세일': 2,
 '절호': 3,
 '충격': 4,
 '특가': 5,
 '특별': 6,
 '폭탄': 7,
 '한정': 8,
 '허경영': 9,
 '홍보': 10,
 '효능': 11}

In [ ]:
cv.transform(email).toarray()

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
cv.fit(ham_dict)
cv.vocabulary_

{'검토': 0, '결제': 1, '고객': 2, '동호회': 3, '배송': 4, '일반': 5, '주문': 6, '확인': 7}

In [ ]:
cv.transform(email).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
ham_fit = cv.fit(ham_dict)

In [ ]:
email_transform_array = spam_fit.transform(email).toarray()
email_transform_array

array([[0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
email_ham_array = ham_fit.transform(email).toarray()
email_ham_array

array([[0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
#영어로

In [ ]:
spam_dict2 = ["advertise", "promotion", "sales", "hu", "special", "sale","member", "company"]
ham_dict2 = ["order", "confirm", "check", "customer", "payment", "send", "general", "club"]

In [ ]:
email = ["promotion !! hu good sales sale check payment"]

In [ ]:
cv.fit(spam_dict2)

CountVectorizer()

In [ ]:
cv.vocabulary_

{'advertise': 0,
 'company': 1,
 'hu': 2,
 'member': 3,
 'promotion': 4,
 'sale': 5,
 'sales': 6,
 'special': 7}

In [ ]:
result1 = cv.transform(email).toarray()
result1

array([[0, 0, 1, 0, 1, 1, 1, 0]])

In [ ]:
cv.fit(ham_dict2)
cv.vocabulary_

{'check': 0,
 'club': 1,
 'confirm': 2,
 'customer': 3,
 'general': 4,
 'order': 5,
 'payment': 6,
 'send': 7}

In [ ]:
result2 = cv.transform(email).toarray()
result2

array([[1, 0, 0, 0, 0, 0, 1, 0]])

In [ ]:
## result1의 0이 아닌 개수의 합, result2의 0이 아닌 개수의 합
result1.sum() #모든 리스트의 합

4

In [ ]:
result2.sum()

2

In [ ]:
result_sum = 0
for item in result1[0]:
  if item!=0:
    result_sum = result_sum+1
result_sum

4

In [ ]:
#감정분류기 연습
# 긍정/부정 사전
# input() 이용해서, 문장을 받으면 긍정인가 부정인가 판단하기
# tf-idf vectorizer 사용

In [ ]:
pos_dict = ["좋아요", "추천", "굿", "괜찮다", "재구매", "싸다", "친절"]
neg_dict = ["별로", "그닥", "비싸다", "비추", "안", "장난", "실망"]

In [ ]:
#example = ["굿 굿 재구매 의향 있습니다. 추천할 만 해요."]
example = input("리뷰 입력 : ")

In [ ]:
tfidf1= TfidfVectorizer()
tfidf2= TfidfVectorizer()

In [ ]:
fitp = tfidf1.fit(pos_dict)
fitn = tfidf2.fit(neg_dict)

In [ ]:
nndarray = tfidf1.transform(example).toarray()
nndarray

array([[0., 0., 1., 0., 0., 0.]])

In [ ]:
nndarray2 = tfidf2.transform(example).toarray()
nndarray2

array([[0., 0., 0., 0., 0., 0.]])

In [ ]:
tfidf1.inverse_transform(nndarray)

[array(['재구매'], dtype='<U3')]

In [ ]:
if nndarray.sum() != 0 :
  if nndarray2().sum() != 0 :
    if nndarray.sum() > nndarray2().sum() :
      print("긍정")
    else:
      print("부정")
  else:
    print("긍정")
elif nndarray2().sum() != 0 :
  print("부정")
else:
  print("몰?루")

In [119]:
from konlpy.tag import Kkma
from konlpy.utils import pprint

ModuleNotFoundError: ignored

In [ ]:
x_data = ["s"]

In [ ]:
for i, document in enumerate(x_data):
  okt = konlpy.tag.Okt()
  clean_words =[]
  for word in okt.pos(document, stem=True): #어간추출
    if word[1] not in ['Josa', 'Eomi', 'Punctuation']: #조사, 어미, 구두
      clean_words.append(word[0])
  print(clean_words)
  document = ''.join(clean_words)
  print(document)
  x_data[i] = document
print(x_data)